FROM hoertech/docker-buildenv:mha_x86_64-linux-gcc-7
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get -y install netpbm fig2dev doxygen graphviz texlive \
                       texlive-latex-extra texlive-font-utils
  git config --global user.email jenkins@build.bot; done
    git config --global user.name jenkins-built-bot

